default_language_version:
  python: python3.10

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: check-added-large-files
  - id: check-ast
  - id: check-builtin-literals
  - id: check-merge-conflict
  - id: detect-private-key
  - id: check-toml
  - id: check-yaml

- repo: https://github.com/psf/black
  rev: 23.7.0
  hooks:
  - id: black
    exclude: ^docs/
    args:
      - --line-length  120
      - --target-version py301
      - --check

- repo: https://github.com/charliermarsh/ruff-pre-commit
  rev: v0.0.287
  hooks:
  - id: ruff
    args:
    - check
    - --target-version py301

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.5.1
  hooks:
  - id: mypy
    exclude: ^docs/
