default_language_version:
  python: python3.10

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: latest
  hooks:
  - id: check-added-large-files
  - id: check-ast
  - id: check-builtin-literals
  - id: check-merge-conflict
  - id: detect-private-key
  - id: check-toml
  - id: check-yaml

- repo: https://github.com/psf/black
  rev: latest
  hooks:
  - id: black
    exclude: ^docs/
    args:
      - --line-length  120
      - --target-version py301
      - --check

- repo: https://github.com/charliermarsh/ruff-pre-commit
  rev: latest
  hooks:
  - id: ruff
    args:
    - check
    - --target-version py301

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: latest
  hooks:
  - id: mypy
    exclude: ^docs/
