name: Release, Build, & Publish yahoo-export

on:
  push:
    tags:
    - ["v*"]
    branches:
    - [main]

defaults:
  run:
    shell: bash

env:
  PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
  PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
#   TEST_PYPI_TOKEN: ${{ secrets.TEST_PYPI_TOKEN }}
  PYPI_USERNAME: __token__

jobs:
  release:
    if: "!startsWith(github.event.head_commit.message, 'bump:')"
    runs-on: [self-hosted]
    name: Bump version, update changelog, create release
    permissions:
      id-token: write

    steps:

    - uses: actions/checkout@v3
      name: Check out
      with:
        token: "${{ secrets.PERSONAL_TOKEN }}"
        fetch-depth: 0

    - uses: commitizen-tools/commitizen-action@master
      name: Create bump and changelog
      with:
        github_token: ${{ secrets.PERSONAL_TOKEN }}
        changelog_increment_filename: CHANGELOG.md

    - uses: softprops/action-gh-release@v1
      name: Release
      with:
        body_path: "CHANGELOG.md"
        tag_name: ${{ env.REVISION }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build:
    name: Build and publish Python 🐍 distributions 📦 to PyPI and TestPyPI
    runs-on: [self-hosted]
    needs:
      - release
    enviornment:
      name: pypi
      url: https://pypi.org/p/yahoo-export
    permissions:
      id-token: write

    steps:

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v4
        name: Set up Python
        with:
          python-version: "3.10"

      - name: Install Hatch
        run: |
          python -m pip install --upgrade pip hatch

      - name: Build package
        run: hatch build

      - uses: pypa/gh-action-pypi-publish@release/v1
        name: Publish distribution 📦 to PyPI
        if: startsWith(github.ref, 'refs/tags')
        with:
          password: $PYPI_TOKEN
          repository-url: https://pypi.org/p/yahoo-export
