name: Bump & Release version

on:
  push:
    branches:
      - master

jobs:
  bump-version:
    if: "!startsWith(github.event.head_commit.message, 'bump:')"
    runs-on: [self-hosted]
    name: Bump version, update changelog, create release

    steps:

      - name: Check out
        uses: actions/checkout@v3
        with:
          token: "${{ secrets.PERSONAL_TOKEN }}"
          fetch-depth: 0

      - name: Create bump and changelog
        uses: commitizen-tools/commitizen-action@master
        with:
          github_token: ${{ secrets.PERSONAL_TOKEN }}
          changelog_increment_filename: CHANGELOG.md

      - uses: softprops/action-gh-release@v1
        name: Release
        with:
          body_path: "CHANGELOG.md"
          tag_name: ${{ env.REVISION }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
