name: Bump Version & Release

on:
  push:
    branches:
    - dev

jobs:
  bump:
    if: ${{ !startsWith(github.event.head_commit.message, 'bump:') }}
    runs-on: [self-hosted]
    name: Bump version, update changelog
    permissions:
      id-token: write

    steps:

    - uses: actions/checkout@v3
      name: Check out
      with:
        token: "${{ secrets.PERSONAL_TOKEN }}"
        fetch-depth: 0
    - uses: actions/setup-python@v3
      name: Set up Python
      with:
        python-version: '3.10'
        cache: 'pip'
        cache-dependency-path: 'requirements-ci.txt'
    - name: Create bump and changelog
      run: |
        git config --global user.email ""
        git config --global user.name "GitHub Actions"
        pip install --upgrade pip
        pip install -r requirements-ci.txt
        cz bump --changelog --devrelease 1
        git push --tags

    - uses: softprops/action-gh-release@v1
      name: Release
      with:
        body_path: "CHANGELOG.md"
        tag_name: ${{ steps.cz.outputs.version }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
